### ISSUE TITLE
TypeError: can only concatenate str (not "WebDriverException") to str

### ISSUE THREAD

**Issue by tailangjun** [gravity0071/cctv_video_spider#1]
$ python web_site_getter.py
Traceback (most recent call last):
  File "/home/tailangjun/Share/DatasetProcessTools/cctv_video_spider/web_site_getter.py", line 123, in <module>
    first_page(video_name_full)
  File "/home/tailangjun/Share/DatasetProcessTools/cctv_video_spider/web_site_getter.py", line 32, in first_page
    browser = webdriver.Chrome()
              ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 209, in __init__
    self.start_session(capabilities)
  File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5628612ade23 <unknown>
#1 0x562860fd67a7 <unknown>
#2 0x56286100150a <unknown>
#3 0x562860ffea25 <unknown>
#4 0x56286103ed92 <unknown>
#5 0x56286103e3af <unknown>
#6 0x562861035de3 <unknown>
#7 0x562861009a7b <unknown>
#8 0x56286100a81e <unknown>
#9 0x56286126f638 <unknown>
#10 0x562861273507 <unknown>
#11 0x56286127dc4c <unknown>
#12 0x562861274136 <unknown>
#13 0x5628612429cf <unknown>
#14 0x562861297b98 <unknown>
#15 0x562861297d68 <unknown>
#16 0x5628612a6cb3 <unknown>
#17 0x7f6981494b43 <unknown>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tailangjun/Share/DatasetProcessTools/cctv_video_spider/web_site_getter.py", line 125, in <module>
    print("ERROR!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" + e)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
TypeError: can only concatenate str (not "WebDriverException") to str

请问是要安装什么依赖吗

**Comment by gravity0071** [comment]
你有在chrome安装chrome的chrome driver嘛



发自我的iPhone


------------------ Original ------------------
From: 太郎君 ***@***.***&gt;
Date: Thu, Dec 7, 2023 5:35 AM
To: gravity0071/cctv_video_spider ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [gravity0071/cctv_video_spider] TypeError: can only concatenate str(not "WebDriverException") to str (Issue #1)





 
$ python web_site_getter.py
 Traceback (most recent call last):
 File "/home/tailangjun/Share/DatasetProcessTools/cctv_video_spider/web_site_getter.py", line 123, in 
 first_page(video_name_full)
 File "/home/tailangjun/Share/DatasetProcessTools/cctv_video_spider/web_site_getter.py", line 32, in first_page
 browser = webdriver.Chrome()
 ^^^^^^^^^^^^^^^^^^
 File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in init
 super().init(
 File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 61, in init
 super().init(command_executor=executor, options=options)
 File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 209, in init
 self.start_session(capabilities)
 File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in start_session
 response = self.execute(Command.NEW_SESSION, caps)["value"]
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
 self.error_handler.check_response(response)
 File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
 raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
 (unknown error: DevToolsActivePort file doesn't exist)
 (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
 Stacktrace:
 #0 0x5628612ade23 
 #1 0x562860fd67a7 
 #2 0x56286100150a 
 #3 0x562860ffea25 
 #4 0x56286103ed92 
 #5 0x56286103e3af 
 #6 0x562861035de3 
 #7 0x562861009a7b 
 #8 0x56286100a81e 
 #9 0x56286126f638 
 #10 0x562861273507 
 #11 0x56286127dc4c 
 #12 0x562861274136 
 #13 0x5628612429cf 
 #14 0x562861297b98 
 #15 0x562861297d68 
 #16 0x5628612a6cb3 
 #17 0x7f6981494b43 
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "/home/tailangjun/Share/DatasetProcessTools/cctv_video_spider/web_site_getter.py", line 125, in 
 print("ERROR!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" + e)
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
 TypeError: can only concatenate str (not "WebDriverException") to str
 
请问是要安装什么依赖吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

**Comment by tailangjun** [comment]
> 你有在chrome安装chrome的chrome driver嘛 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: 太郎君 ***@***.***&gt; Date: Thu, Dec 7, 2023 5:35 AM To: gravity0071/cctv_video_spider ***@***.***&gt; Cc: Subscribed ***@***.***&gt; Subject: Re: [gravity0071/cctv_video_spider] TypeError: can only concatenate str(not "WebDriverException") to str (Issue #1) $ python web_site_getter.py Traceback (most recent call last): File "/home/tailangjun/Share/DatasetProcessTools/cctv_video_spider/web_site_getter.py", line 123, in first_page(video_name_full) File "/home/tailangjun/Share/DatasetProcessTools/cctv_video_spider/web_site_getter.py", line 32, in first_page browser = webdriver.Chrome() ^^^^^^^^^^^^^^^^^^ File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in init super().init( File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 61, in init super().init(command_executor=executor, options=options) File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 209, in init self.start_session(capabilities) File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in start_session response = self.execute(Command.NEW_SESSION, caps)["value"] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute self.error_handler.check_response(response) File "/opt/anaconda3/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally. (unknown error: DevToolsActivePort file doesn't exist) (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) Stacktrace: #0 0x5628612ade23 #1 0x562860fd67a7 #2 0x56286100150a #3 0x562860ffea25 #4 0x56286103ed92 #5 0x56286103e3af #6 0x562861035de3 #7 0x562861009a7b #8 0x56286100a81e #9 0x56286126f638 #10 0x562861273507 #11 0x56286127dc4c #12 0x562861274136 #13 0x5628612429cf #14 0x562861297b98 #15 0x562861297d68 #16 0x5628612a6cb3 #17 0x7f6981494b43 During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/tailangjun/Share/DatasetProcessTools/cctv_video_spider/web_site_getter.py", line 125, in print("ERROR!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" + e) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~ TypeError: can only concatenate str (not "WebDriverException") to str 请问是要安装什么依赖吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

没有，我试一下，谢谢

**Comment by tailangjun** [comment]
安装后现在恢复正常了，楼主🐂🍺呀，非常感谢
话说我如果要下载某搜索结果中的视频，比方说 https://search.cctv.com/search.php?qtext=%E6%96%B0%E9%97%BB%E5%BF%AB%E8%AF%84&type=video，是不是得修改 browser.find_element_by_中的节点名呀

/Users/tailangjun/Downloads/cctv_video_spider/web_site_getter.py:21: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  source_link_element = video_browser.find_element_by_xpath('//video[@id="_video_player_html5_api"]/source')
downloading: 20231203.mp4m
100%|█████████████████████████████████████████████████████████████| 181/181 [02:59<00:00,  1.01it/s]
